name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set Node.js options
      run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

    - name: Type check
      run: npx tsc --noEmit

    - name: Build test
      run: npm run build 